### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER] with v0.6

### ISSUE THREAD

**Issue by CoolWolf69** [sebw/pushtify#2]
Hello,
was anyone able to successfully deploy v0.6?

When I deploy v0.6 I receive following output in the log:
pushtify  | [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
pushtify  | ### closed ###

and the container continues rebooting (loop).

v0.5 works flawlessly ... so this is the one I am currently using. Any idea how to get around the SSL issue in v0.6?

Thanks,
CoolWolf69

**Comment by sebw** [comment]
0.6 connects using secure websocket (wss://). 

0.5 was not (ws://). 

Is your certificate valid? I use let's encrypt myself without issue. 

Cheers.

**Comment by CoolWolf69** [comment]
Thanks for your feedback and for pointing me in the right direction @sebw !

I previously used an IP address (and Port) for my GOTIFY_HOST env variable. After I switched it to a hostname (with a vaild let's encrypt certificate) there is no SSL error anymore in v0.6 :-)

Closing thread now.

Cheers!

**Comment by CoolWolf69** [comment]
THANKS!
